/* DO NOT EDIT, file generated by nestjs-i18n */

/* eslint-disable */
/* prettier-ignore */
import type { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "errors": {
        "INTERNAL_SERVER_ERROR": string;
        "DATABASE_CONNECTION_REFUSED": string;
        "UNIQU_CONSTRAINT_FAILED": string;
        "UNIQU_CONSTRAINT_MODEL_FAILED": string;
        "duplicate_value": string;
        "validation_failed": string;
        "make_sure_inputs_are_valid": string;
        "invalid_credentials": string;
        "user_not_found": string;
        "account_not_verified": string;
        "invalid_token": string;
        "forbidden": string;
        "invalid_verification_token": string;
    };
    "fields": {
        "email": string;
        "password": string;
        "firstName": string;
        "lastName": string;
        "username": string;
        "name": string;
    };
    "messages": {
        "success": string;
        "account": {
            "created": string;
            "updated": string;
            "verify_email": string;
            "verified": string;
            "password_changed": string;
            "deleted": string;
            "deactivated": string;
            "reactivated": string;
            "login": string;
            "logout": string;
            "password_reset": string;
            "password_reset_success": string;
            "MFA_enabled": string;
            "MFA_disabled": string;
            "OTP_sent": string;
            "OTP_verified": string;
            "session_expired": string;
            "account_locked": string;
            "account_unlocked": string;
            "suspended": string;
            "unsuspended": string;
        };
        "post": {
            "created": string;
            "published": string;
            "updated": string;
            "deleted": string;
            "rejected": string;
            "reported": string;
            "not_found": string;
            "already_reported": string;
            "blocked": string;
            "unblocked": string;
        };
    };
    "validations": {
        "email": {
            "is_not_correct": string;
            "is_required": string;
        };
        "password": {
            "is_required": string;
            "length": string;
            "not_confirmed": string;
        };
        "firstName": {
            "is_required": string;
            "is_string": string;
            "length": string;
        };
        "lastName": {
            "is_string": string;
            "length": string;
        };
        "provider": {
            "is_not_correct": string;
        };
        "verifyEmail": {
            "is_required": string;
            "invalid": string;
            "expired": string;
        };
        "title": {
            "is_required": string;
            "is_string": string;
            "length": string;
        };
        "content": {
            "is_required": string;
            "is_string": string;
            "length": string;
        };
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
